config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'

  devise_for :users

  resources :attendances
  resources :events
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!--Title changes depending on the view -->
    <title><%= yield(:title) %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class='bg-light'>

  <header>
    <!-- Bootstrap navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  </a>
      <%= link_to 'Eventbrite', events_path, :class => 'navbar-brand' %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Add an event', new_event_path, :class => 'nav-link' %>
          </li>
        </ul>

        <!-- Dropdowns depending on session status -->
        <ul class="navbar-nav ml-auto">
          <!-- if connected, profile and logout options -->
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.first_name.capitalize %>
              </a>
              <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                <%= link_to 'My profile', user_path(current_user.id), :class => "dropdown-item text-light" %>
                <%= link_to 'Log  out', destroy_user_session_path,method: :delete, :class => "dropdown-item text-light" %>
              </div>
            </li>

          <!-- if not connected, login and signup options -->
          <% else%>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Log in / Sign up
              </a>
              <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                <%= link_to 'Log in', new_user_session_path, :class => "dropdown-item text-light" %>
                <%= link_to 'Sign up', new_user_registration_path, :class => "dropdown-item text-light" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

  <!-- Displaying alerts and notices -->
  <% if notice || alert %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <% end %>
  
  <!-- Getting content from the other views -->
  <main role='main'>
    <%= yield %>
  </main>
  
  </body>
</html>